aux_loss: true
backbone: resnet50
batch_size: 1
bbox_loss_coef: 5.0
clip_max_norm: 0.1
cls_loss_coef: 2.0
coco_and_crowdhuman_prev_frame_rnd_augs: 0.2
coco_min_num_objects: 0
coco_panoptic_path: null
coco_path: data/HT21
coco_person_train_split: null
crowdhuman_path: data/HT21
crowdhuman_train_split: null
dataset: HT21
debug: false
dec_layers: 6
dec_n_points: 4
deformable: true
device: cuda
dice_loss_coef: 1.0
dilation: false
dim_feedforward: 1024
dist_backend: nccl
dist_url: env://
distributed: true
dropout: 0.1
enc_layers: 6
enc_n_points: 4
eos_coef: 0.1
epochs: 10
eval_only: false
eval_train: false
focal_alpha: 0.25
focal_gamma: 2
focal_loss: true
freeze_detr: false
giou_loss_coef: 2
gpu: 0
hidden_dim: 288
img_transform: !!python/object:argparse.Namespace
  max_size: 1333
  val_width: 800
load_mask_head_from_model: null
lr: 0.0002
lr_backbone: 2.0e-05
lr_backbone_names:
- backbone.0
lr_drop: 10
lr_linear_proj_mult: 0.1
lr_linear_proj_names:
- reference_points
- sampling_offsets
lr_track: 0.0001
mask_loss_coef: 1.0
masks: false
merge_frame_features: false
mot_path_train: data/HT21
mot_path_val: data/HT21
multi_frame_attention: true
multi_frame_attention_separate_encoder: true
multi_frame_encoding: true
nheads: 8
no_vis: false
num_feature_levels: 4
num_queries: 500
num_workers: 2
output_dir: models/custom_dataset_deformable
overflow_boxes: true
overwrite_lr_scheduler: false
overwrite_lrs: false
position_embedding: sine
pre_norm: false
rank: 0
resume: models/mot20_crowdhuman_deformable_multi_frame/checkpoint_epoch_50.pth
resume_optim: false
resume_shift_neuron: false
resume_vis: false
save_model_interval: 5
seed: 42
set_cost_bbox: 5.0
set_cost_class: 2.0
set_cost_giou: 2.0
start_epoch: 1
track_attention: false
track_backprop_prev_frame: false
track_prev_frame_range: 5
track_prev_frame_rnd_augs: 0.01
track_prev_prev_frame: false
track_query_false_negative_prob: 0.4
track_query_false_positive_eos_weight: true
track_query_false_positive_prob: 0.1
tracking: true
tracking_eval: true
train_split: HT21_train_1_coco
two_stage: false
val_interval: 5
val_split: HT21_val_1_coco
vis_and_log_interval: 50
vis_port: 8090
vis_server: ''
weight_decay: 0.0001
with_box_refine: true
world_size: 6
